/*
  作用：定义action的type类型
 */

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const UPDATE_USERINFO = 'UPDATE_USERINFO';
export const RESET_USERINFO = 'RESET_USERINFO';

export const UPDATE_USERLIST = 'UPDATE_USERLIST';
export const RESET_USERLIST = 'RESET_USERLIST';
export const GET_CHAT_MESSAGES = 'GET_CHAT_MESSAGES';
export const RESET_CHAT_MESSAGES = 'RESET_CHAT_MESSAGES';
export const UPDATE_CHAT_MESSAGES = 'UPDATE_CHAT_MESSAGES';